### ISSUE TITLE
.NET Core Solution

### ISSUE THREAD

**Issue by danstur** [BepInEx/NRedirect#1]
I just stumbled upon [your blog post](https://bepis.io/blog/1/) which mentioned ".NET Core / .NET Framework 5 may or may not be in the future since they don't have AppDomains "

I thought I'd point you towards [this](https://github.com/dotnet/runtime/blob/main/docs/design/features/host-startup-hook.md) feature available since .NET Core 3 which I think might save you some effort.

**Comment by bbepis** [comment]
Hey, sorry I forgot to reply to this.

Thanks for the heads up, this seems to be an adequate solution for .NET Core 3.1 and up. AFAIK this could work for Steam games since Steam lets you provide additional environment variables to games (at least on Linux, not sure about windows)
